<a href="https://colab.research.google.com/github/unnibr1777/Flight_Delay_Recommendation_ANN/blob/main/ANN_flight_duration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Flight Delay Recommendation/T_ONTIME_REPORTING.csv")#, names=column_names)

In [ ]:
df.head(5)

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK               FL_DATE  \
0  2023        1      1             1            7  1/1/2023 12:00:00 AM   
1  2023        1      1             1            7  1/1/2023 12:00:00 AM   
2  2023        1      1             1            7  1/1/2023 12:00:00 AM   
3  2023        1      1             1            7  1/1/2023 12:00:00 AM   
4  2023        1      1             1            7  1/1/2023 12:00:00 AM   

  OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID OP_CARRIER  OP_CARRIER_FL_NUM  ...  \
0                9E                  20363         9E               4647  ...   
1                9E                  20363         9E               4650  ...   
2                9E                  20363         9E               4650  ...   
3                9E                  20363         9E               4654  ...   
4                9E                  20363         9E               4663  ...   

   CANCELLATION_CODE  DIVERTED  CRS_ELAPSED_TIME ACTUAL_ELAPSED_TIME AIR_TIME  \
0                NaN       0.0             122.0                97.0     72.0   
1                NaN       0.0             117.0               107.0     82.0   
2                NaN       0.0             146.0               119.0     91.0   
3                NaN       0.0             141.0               123.0     89.0   
4                NaN       0.0             208.0               203.0    174.0   

   FLIGHTS  CARRIER_DELAY  WEATHER_DELAY SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0      1.0            NaN            NaN            NaN                  NaN  
1      1.0            NaN            NaN            NaN                  NaN  
2      1.0            NaN            NaN            NaN                  NaN  
3      1.0            NaN            NaN            NaN                  NaN  
4      1.0            NaN            NaN            NaN                  NaN  

[5 rows x 36 columns]

In [ ]:
df.shape

(59610, 36)

In [ ]:
df.dtypes

YEAR                       int64
QUARTER                    int64
MONTH                      int64
DAY_OF_MONTH               int64
DAY_OF_WEEK                int64
FL_DATE                   object
OP_UNIQUE_CARRIER         object
OP_CARRIER_AIRLINE_ID      int64
OP_CARRIER                object
OP_CARRIER_FL_NUM          int64
ORIGIN_AIRPORT_ID          int64
ORIGIN_AIRPORT_SEQ_ID      int64
ORIGIN_CITY_MARKET_ID      int64
ORIGIN_CITY_NAME          object
ORIGIN_STATE_ABR          object
DEST_AIRPORT_ID            int64
DEST_AIRPORT_SEQ_ID        int64
DEST_CITY_MARKET_ID        int64
DEST_CITY_NAME            object
DEP_TIME                 float64
DEP_DELAY                float64
DEP_DELAY_NEW            float64
ARR_TIME                 float64
ARR_DELAY                float64
ARR_DELAY_NEW            float64
CANCELLED                float64
CANCELLATION_CODE         object
DIVERTED                 float64
CRS_ELAPSED_TIME         float64
ACTUAL_ELAPSED_TIME      float64
AIR_TIME  

In [ ]:
column_dtypes = df.dtypes.value_counts()

print(column_dtypes)

float64    16
int64      13
object      7
dtype: int64


In [ ]:
df.isnull().sum()

YEAR                         0
QUARTER                      0
MONTH                        0
DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
FL_DATE                      0
OP_UNIQUE_CARRIER            0
OP_CARRIER_AIRLINE_ID        0
OP_CARRIER                   0
OP_CARRIER_FL_NUM            0
ORIGIN_AIRPORT_ID            0
ORIGIN_AIRPORT_SEQ_ID        0
ORIGIN_CITY_MARKET_ID        0
ORIGIN_CITY_NAME             0
ORIGIN_STATE_ABR             0
DEST_AIRPORT_ID              0
DEST_AIRPORT_SEQ_ID          0
DEST_CITY_MARKET_ID          0
DEST_CITY_NAME               0
DEP_TIME                   823
DEP_DELAY                  824
DEP_DELAY_NEW              824
ARR_TIME                   880
ARR_DELAY                 1004
ARR_DELAY_NEW             1004
CANCELLED                    0
CANCELLATION_CODE        58738
DIVERTED                     0
CRS_ELAPSED_TIME             0
ACTUAL_ELAPSED_TIME       1004
AIR_TIME                  1004
FLIGHTS                      0
CARRIER_

In [ ]:
# Assuming you have a DataFrame called 'df' and a categorical column called 'Category'
value_counts = df['CANCELLED'].value_counts()

print(value_counts)

0.0    58738
1.0      872
Name: CANCELLED, dtype: int64


In [ ]:
df["QUARTER"].unique()

array([1])

In [ ]:
data =df.copy()

In [ ]:
data.drop(["YEAR","QUARTER","MONTH", "FL_DATE","OP_CARRIER_AIRLINE_ID", "ORIGIN_AIRPORT_SEQ_ID","DEST_AIRPORT_SEQ_ID","CANCELLATION_CODE"], axis=1,inplace= True)

In [ ]:
data.drop(["ARR_DELAY_NEW","DEP_DELAY_NEW",], axis=1,inplace= True)

In [ ]:
data.head()

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER OP_CARRIER  OP_CARRIER_FL_NUM  \
0             1            7                9E         9E               4647   
1             1            7                9E         9E               4650   
2             1            7                9E         9E               4650   
3             1            7                9E         9E               4654   
4             1            7                9E         9E               4663   

   ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID ORIGIN_CITY_NAME ORIGIN_STATE_ABR  \
0              12953                  31703     New York, NY               NY   
1              11996                  31871        Greer, SC               SC   
2              12953                  31703     New York, NY               NY   
3              12478                  31703     New York, NY               NY   
4              12478                  31703     New York, NY               NY   

   DEST_AIRPORT_ID  ...  CANCELLED DIVERTED  CRS_ELAPSED_TIME  \
0            14492  ...        0.0      0.0             122.0   
1            12953  ...        0.0      0.0             117.0   
2            11996  ...        0.0      0.0             146.0   
3            11433  ...        0.0      0.0             141.0   
4            13487  ...        0.0      0.0             208.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  CARRIER_DELAY  WEATHER_DELAY  \
0                 97.0      72.0      1.0            NaN            NaN   
1                107.0      82.0      1.0            NaN            NaN   
2                119.0      91.0      1.0            NaN            NaN   
3                123.0      89.0      1.0            NaN            NaN   
4                203.0     174.0      1.0            NaN            NaN   

   SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0             NaN                  NaN  
1             NaN                  NaN  
2             NaN                  NaN  
3             NaN                  NaN  
4             NaN                  NaN  

[5 rows x 26 columns]

In [ ]:
for u, x, y in zip(data.columns,data.dtypes,data.isnull().sum()):
  print(y,x,u)

0 int64 DAY_OF_MONTH
0 int64 DAY_OF_WEEK
0 object OP_UNIQUE_CARRIER
0 object OP_CARRIER
0 int64 OP_CARRIER_FL_NUM
0 int64 ORIGIN_AIRPORT_ID
0 int64 ORIGIN_CITY_MARKET_ID
0 object ORIGIN_CITY_NAME
0 object ORIGIN_STATE_ABR
0 int64 DEST_AIRPORT_ID
0 int64 DEST_CITY_MARKET_ID
0 object DEST_CITY_NAME
823 float64 DEP_TIME
824 float64 DEP_DELAY
880 float64 ARR_TIME
1004 float64 ARR_DELAY
0 float64 CANCELLED
0 float64 DIVERTED
0 float64 CRS_ELAPSED_TIME
1004 float64 ACTUAL_ELAPSED_TIME
1004 float64 AIR_TIME
0 float64 FLIGHTS
45995 float64 CARRIER_DELAY
45995 float64 WEATHER_DELAY
45995 float64 SECURITY_DELAY
45995 float64 LATE_AIRCRAFT_DELAY


In [ ]:
data.head(5)

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER OP_CARRIER  OP_CARRIER_FL_NUM  \
0             1            7                9E         9E               4647   
1             1            7                9E         9E               4650   
2             1            7                9E         9E               4650   
3             1            7                9E         9E               4654   
4             1            7                9E         9E               4663   

   ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID ORIGIN_CITY_NAME ORIGIN_STATE_ABR  \
0              12953                  31703     New York, NY               NY   
1              11996                  31871        Greer, SC               SC   
2              12953                  31703     New York, NY               NY   
3              12478                  31703     New York, NY               NY   
4              12478                  31703     New York, NY               NY   

   DEST_AIRPORT_ID  ...  CANCELLED DIVERTED  CRS_ELAPSED_TIME  \
0            14492  ...        0.0      0.0             122.0   
1            12953  ...        0.0      0.0             117.0   
2            11996  ...        0.0      0.0             146.0   
3            11433  ...        0.0      0.0             141.0   
4            13487  ...        0.0      0.0             208.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  CARRIER_DELAY  WEATHER_DELAY  \
0                 97.0      72.0      1.0            NaN            NaN   
1                107.0      82.0      1.0            NaN            NaN   
2                119.0      91.0      1.0            NaN            NaN   
3                123.0      89.0      1.0            NaN            NaN   
4                203.0     174.0      1.0            NaN            NaN   

   SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0             NaN                  NaN  
1             NaN                  NaN  
2             NaN                  NaN  
3             NaN                  NaN  
4             NaN                  NaN  

[5 rows x 26 columns]

In [ ]:
# Assuming you have a DataFrame called 'data' and want to replace null values with 0 in specific columns
for feature in ["CARRIER_DELAY", "WEATHER_DELAY", "SECURITY_DELAY", "LATE_AIRCRAFT_DELAY"]:
    data[feature] = data[feature].fillna(0)


In [ ]:

# Assuming you have a DataFrame called 'data' and want to fill null values with the mean in specific columns
columns_to_fill = ["ACTUAL_ELAPSED_TIME", "AIR_TIME","DEP_TIME", "DEP_DELAY", "ARR_TIME","ARR_DELAY"]

for column in columns_to_fill:
    data[column].fillna(data[column].mean(), inplace=True)

In [ ]:
for u, x, y in zip(data.columns,data.dtypes,data.isnull().sum()):
  print(y,x,u)

0 int64 DAY_OF_MONTH
0 int64 DAY_OF_WEEK
0 int64 OP_UNIQUE_CARRIER
0 int64 OP_CARRIER
0 int64 OP_CARRIER_FL_NUM
0 int64 ORIGIN_AIRPORT_ID
0 int64 ORIGIN_CITY_MARKET_ID
0 int64 ORIGIN_CITY_NAME
0 int64 ORIGIN_STATE_ABR
0 int64 DEST_AIRPORT_ID
0 int64 DEST_CITY_MARKET_ID
0 int64 DEST_CITY_NAME
0 float64 DEP_TIME
0 float64 DEP_DELAY
0 float64 ARR_TIME
0 float64 ARR_DELAY
0 float64 CANCELLED
0 float64 DIVERTED
0 float64 CRS_ELAPSED_TIME
0 float64 ACTUAL_ELAPSED_TIME
0 float64 AIR_TIME
0 float64 FLIGHTS
0 float64 CARRIER_DELAY
0 float64 WEATHER_DELAY
0 float64 SECURITY_DELAY
0 float64 LATE_AIRCRAFT_DELAY


In [ ]:
data.shape

(59610, 26)

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Assuming you have a DataFrame called 'data' with categorical columns
categorical_columns = ["OP_UNIQUE_CARRIER","OP_CARRIER","ORIGIN_CITY_NAME", "ORIGIN_STATE_ABR", "DEST_CITY_NAME"]

label_encoder = LabelEncoder()

for column in categorical_columns:
    data[column] = label_encoder.fit_transform(data[column])

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input


# Split the input features (X) and target variables (y)
X = data.drop(['ACTUAL_ELAPSED_TIME'], axis=1)
y_flight_duration = data['ACTUAL_ELAPSED_TIME']


# Split the data into training and testing sets
X_train, X_test, y_train_flight_duration,y_test_flight_duration = train_test_split(
    X,y_flight_duration, test_size=0.2, random_state=42
)

# Scale numerical features if necessary
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)          ## transfroming the test data with learning parameters of train data itself , so fit is not used inoder to avoid data leankage of test data


In [ ]:
X_train_scaled

array([[-1.23587182,  0.56937999, -0.59545213, ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 0.37774647,  0.56937999, -0.59545213, ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 0.14722957, -0.39848887, -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466],
       ...,
       [-1.81216406,  1.53724886, -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466],
       [-0.77483802, -0.8824233 , -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 1.53033096, -1.36635773, -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466]])

In [ ]:
X_train_scaled.shape

(47688, 25)

In [ ]:
X_test_scaled

array([[ 0.83878026, -0.8824233 ,  1.09916351, ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 1.64558941, -0.8824233 , -0.97203338, ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 0.14722957, -0.39848887, -0.59545213, ..., -0.04572394,
        -0.02579494, -0.21654466],
       ...,
       [-0.77483802, -0.8824233 , -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 0.26248802,  0.08544556, -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466],
       [ 1.64558941, -0.8824233 , -0.4071615 , ..., -0.04572394,
        -0.02579494, -0.21654466]])

In [ ]:

## Part 2 Now lets create the ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU,ReLU
from tensorflow.keras.layers import Dropout

In [ ]:
### Lets initialize the ANN
regressor=Sequential()

In [ ]:
## Adding the input Layer and first hidden layer
regressor.add(Dense(10,input_shape=(25,),activation='relu'))

In [ ]:
regressor

In [ ]:
# adding the first hidden layer
regressor.add(Dense(units=10,activation='relu'))
#classifier.add(Dropout(0.2))

In [ ]:
##adding the second hidden layer
regressor.add(Dense(units=10,activation='relu'))
#classifier.add(Dropout(0.3))

In [ ]:
##  Adding the output layer
regressor.add(Dense(1,activation='linear'))

In [ ]:
regressor.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 10)                260       
                                                                 
 dense_5 (Dense)             (None, 10)                110       
                                                                 
 dense_6 (Dense)             (None, 10)                110       
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
Total params: 491
Trainable params: 491
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [ ]:
regressor.compile(optimizer=opt, loss='mean_squared_error', metrics=['mean_absolute_error'])

In [ ]:
## Early Stopping
import tensorflow as tf
early_stopping=tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5

)

In [ ]:
X_train.shape

(47688, 25)

In [ ]:
model_history=regressor.fit(X_train_scaled,y_train_flight_duration,validation_data=(X_test_scaled,y_test_flight_duration),batch_size=10,epochs=10,callbacks=early_stopping)

Epoch 1/10
4769/4769 [==============================] - 18s 4ms/step - loss: 193.8158 - mean_absolute_error: 4.2534 - val_loss: 57.7228 - val_mean_absolute_error: 3.5012
Epoch 2/10
4769/4769 [==============================] - 19s 4ms/step - loss: 44.5238 - mean_absolute_error: 2.5500 - val_loss: 16.3301 - val_mean_absolute_error: 1.0980
Epoch 3/10
4769/4769 [==============================] - 20s 4ms/step - loss: 20.2699 - mean_absolute_error: 2.0886 - val_loss: 7.5347 - val_mean_absolute_error: 1.0665
Epoch 4/10
4769/4769 [==============================] - 21s 4ms/step - loss: 11.7861 - mean_absolute_error: 1.4841 - val_loss: 11.9628 - val_mean_absolute_error: 1.3316
Epoch 5/10
4769/4769 [==============================] - 27s 6ms/step - loss: 12.6965 - mean_absolute_error: 1.3774 - val_loss: 10.3817 - val_mean_absolute_error: 1.1922
Epoch 6/10
4769/4769 [==============================] - 21s 4ms/step - loss: 10.2049 - mean_absolute_error: 1.4352 - val_loss: 7.5194 - val_mean_absolute_e

In [ ]:
# ... Existing code ...

# Save the trained model
regressor.save("ann_model.h5")

# Load the saved model
from tensorflow.keras.models import load_model
loaded_model = load_model("ann_model.h5")

# Make predictions using the loaded model
predicted_flight_duration = loaded_model.predict(X_test_scaled)

373/373 [==============================] - 1s 3ms/step


In [ ]:
predicted_flight_duration

array([[124.448326],
       [413.07455 ],
       [203.77895 ],
       ...,
       [293.36703 ],
       [182.10481 ],
       [ 62.32234 ]], dtype=float32)

In [ ]:
df_duration = pd.DataFrame(predicted_flight_duration)
df_duration.max(), df_duration.min()

(0    725.431641
 dtype: float32,
 0    49.014805
 dtype: float32)

In [ ]:
df['ACTUAL_ELAPSED_TIME'].max()

749.0

In [ ]:
pd.DataFrame(predicted_flight_duration).head(20)

0
0   124.448326
1   413.074554
2   203.778946
3   138.396576
4   159.954025
5    80.759651
6   130.315613
7   166.599106
8    74.714592
9   132.613617
10  131.305435
11  579.043335
12  355.971405
13  102.133514
14  154.072342
15  154.481049
16   91.973373
17  338.906189
18  107.127213
19  121.765831